pipeline:
  docker:
    repo: armswarm/odyn
    build_args:
      - ODYN_VERSION=0.1.0
      - VCS_REF=${DRONE_COMMIT_SHA}
      - VCS_URL=${DRONE_REPO_LINK}
      - BUILD_DATE=${DRONE_BUILD_CREATED}
      - PROJECT_NAME=${DRONE_REPO}
    tag: [ "latest", "0.1", "0.1.0" ]
    when:
      branch: master
      event: push

  slack:
    when:
      status: [ failure, success ]
